<?php
/**
 * MageVision Blog8
 *
 * @category     MageVision
 * @package      MageVision_Blog8
 * @author       MageVision Team
 * @copyright    Copyright (c) 2016 MageVision (https://www.magevision.com)
 * @license      http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $items = $block->getItems(); ?>
<?php foreach ($items as $item): ?>
    <p><?php echo $item->getName(); ?></p>
<?php endforeach; ?>
