<?php
/**
 * MageVision Blog51
 *
 * @category     MageVision
 * @package      MageVision_Blog51
 * @author       MageVision Team
 * @copyright    Copyright (c) 2019 MageVision (https://www.magevision.com)
 * @license      http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?= $block->escapeHtml(__(
    'Please <a href="%1">click here</a> to redirect to your account.',
    $block->getData('url')
), ['a']);
?>